# Generated by Django 3.1 on 2020-08-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='item',
            name='article',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
